resource_group       = "myresourcegroup"
location             = "Australia East"
storage_account      = "mystorageaccount"
search_service       = "mysearchservice"
sku                  = "S0"
cognitive_account    = "mycognitiveaccount"
storage_container    = "mystoragecontainer"
