resource_group  = "resource_group"
location        = "location"
storage_account = "storage_account"
search_service  = "search_service"
sku = "sku"
cognitive_account = "cognitive_account"
storage_container = "container"
