trigger:
 - main

jobs:
 - job: Terraform
   pool:
    vmImage: 'ubuntu-latest'

env:
    ARM_CLIENT_ID: ${{ secrets.clientId }}
    ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
    ARM_TENANT_ID: ${{ secrets.tenantId }}

steps: 
  - task: UseTerraform@0
    inputs:
      terraformVersion: '1.4.x'

  - script: |
     terraform init
     displayName: 'Initialize Terraform'

  - script: |
      terraform plan -var-file=terraform.tfvars
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -var-file=terraform.tfvars -auto-approve
  displayName: 'Terraform Apply'
