trigger:
- main

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: '1.4.x'
    
  - script: |
      terraform init
    displayName: 'Initialize Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.clientId }}
      ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
      ARM_TENANT_ID: ${{ secrets.tenantId }}

  - script: |
      terraform plan -var-file=terraform.tfvars
    displayName: 'Terraform Plan'
    env:
      ARM_CLIENT_ID: ${{ secrets.clientId }}
      ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
      ARM_TENANT_ID: ${{ secrets.tenantId }}

  - script: |
      terraform apply -var-file=terraform.tfvars -auto-approve
    displayName: 'Terraform Apply'
    env:
      ARM_CLIENT_ID: ${{ secrets.clientId }}
      ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.subscriptionId }}
      ARM_TENANT_ID: ${{ secrets.tenantId }}
