name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Update to the version you need

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars

    - name: Terraform Apply
      run: terraform apply -var-file=terraform.tfvars -auto-approve
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
