trigger:
- main  # Change this to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Your-Azure-Subscription'  # Change this to your Azure subscription service connection
  resourceGroup: 'myproj_resource_group'
  location: 'Australia East'
  tfVersion: '1.5.0'  # Use the appropriate version of Terraform

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Install Terraform
      curl -LO https://releases.hashicorp.com/terraform/$(tfVersion)/terraform_$(tfVersion)_linux_amd64.zip
      unzip terraform_$(tfVersion)_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version

- task: TerraformInstaller@0
  inputs:
    terraformVersion: $(tfVersion)

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
