name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
   
    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
   
    - name: Terraform Apply
      run: terraform apply -var-file="terraform.tfvars" -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_ACTIVE_DIRECTORY_ENDPOINT_URL: ${{ secrets.AZURE_ACTIVE_DIRECTORY_ENDPOINT_URL }}
        AZURE_RESOURCE_MANAGER_ENDPOINT_URL: ${{ secrets.AZURE_RESOURCE_MANAGER_ENDPOINT_URL }}
        AZURE_ACTIVE_DIRECTORY_GRAPH_RESOURCE_ID: ${{ secrets.AZURE_ACTIVE_DIRECTORY_GRAPH_RESOURCE_ID }}
        AZURE_SQL_MANAGEMENT_ENDPOINT_URL: ${{ secrets.AZURE_SQL_MANAGEMENT_ENDPOINT_URL }}
        AZURE_GALLERY_ENDPOINT_URL: ${{ secrets.AZURE_GALLERY_ENDPOINT_URL }}
        AZURE_MANAGEMENT_ENDPOINT_URL: ${{ secrets.AZURE_MANAGEMENT_ENDPOINT_URL }}
